load database
  from sqlite:///var/lib/hass/home-assistant_v2.db.backup
  into postgresql://homeassistant@/homeassistant
with data only, drop indexes, reset sequences, truncate;

pg_dump hass --schema-only | grep 'ADD GENERATED BY DEFAULT AS IDENTITY' | awk '{ print "SELECT setval('\''" $3 "_" $6 "_seq'\'', (SELECT MAX("$6") FROM "$3"));" }' | psql hass